---
- name: this playbook install package
  hosts: all
  become: true
  tasks:
  - name: Install package
    yum:
      name: "{{item}}"
      state: installed
    with_items:
      - git
    when: ansible_os_family == "RedHat"
  - name: Install package
    apt:
      name: "{{item}}"
      state: present
    with_items:
      - git
    when: ansible_os_family == "Debain"
