---
- name: This playboo for httpd
  hosts: webservers
  become: true
  tasks:
  - name: install httpd package
    yum:
      name: httpd
      state: installed
    notify: service start for httpd

  handlers:
  - name: service start for httpd
    service:
      name: httpd
      state: started
