---
- name: this playbook install packages
  hosts: all
  become: true
  tasks:
  - name: install packages
    yum:
      name: ['git', 'make', 'gcc', 'wget', 'telnet', 'gzip']
      state: installed
